# Generated by Django 5.2.9 on 2025-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('vest_date', models.DateTimeField(verbose_name='When do your stocks vest?')),
            ],
        ),
    ]
